src/views/GrampsjsViewPlaces.js
The column "title" in the places list view always showed an empty column header.
This fixes this to show the correct header "Title".
=> Fix title of column "title" in places list

.dockerignore, dev/Dockerfile.api, dev/Dockerfile.frontend, dev/config.cfg, dev/nginx.conf, docker-compose.yml
Added Docker Compose setup for easier development.
The frontend and the api are running in separate docker containers. In order to run them on a single port there is reverse proxy added. The reverse proxy forwards all `/api` request to the `gramps-api` container and all other requests go to the `gramps-frontend` container.
The frontend is running in a dev server that makes development without rebuild possible. It also enables auto reload in the browser.
=> Docker compose for easier development

src/components/GrampsjsFilterType.js, src/components/GrampsjsFormChildRef.js, src/components/GrampsjsFormEditAttribute.js, src/components/GrampsjsFormEditName.js, src/components/GrampsjsFormEditUrl.js, src/components/GrampsjsFormEventRef.js, src/components/GrampsjsFormName.js, src/components/GrampsjsFormNoteRef.js, src/components/GrampsjsFormRepoRef.js, src/components/GrampsjsFormSelectType.js, src/components/GrampsjsFormSurname.js, src/mixins/GrampsjsNewNoteMixin.js, src/views/GrampsjsViewNewEvent.js, src/views/GrampsjsViewNewPlace.js, src/views/GrampsjsViewNewRepository.js
solves issue in the comment
https://github.com/gramps-project/Gramps.js/issues/123#issuecomment-1307770959
=> Fix initial value in type selectbox

src/components/GrampsjsFormSelectDate.js, src/lang/en.json, src/util.js, src/views/GrampsjsViewNewCitation.js, src/views/GrampsjsViewNewEvent.js, src/views/GrampsjsViewNewMedia.js, src/views/GrampsjsViewNewPerson.js
- separate input fields for year, month, date to enable #160 
- button opens native date picker (optional - will populate separate inputs) fixing #156 (see also #112)
=> Revamp date select component (fixes #160, fixes #156)

src/charts/FanChart.js, src/components/GrampsjsFanChart.js
Pretty similar to #184, although here it is a bit easier to get the actual sizes
Instead of assuming that the fan chart is a perfect circle of radius 60 * <ancestor generations> + 30, this calculates the bounding box of the ancestor arcs that are actually drawn.
Before:
https://user-images.githubusercontent.com/4743325/221392267-66532cd2-f0af-4c4c-b75f-797245253c2f.mov
After:
https://user-images.githubusercontent.com/4743325/221392274-c85fdac9-b4b8-431c-9127-b5608bde5a62.mov
=> Better estimation of fan chart size

src/SharedStyles.js, src/api.js, src/components/GrampsjsTaskProgressIndicator.js, src/views/GrampsjsViewExport.js, src/views/GrampsjsViewSettings.js
This uses the task queue for generating exports if available, but also works without it. A status icon shows whether generating the exoprt is still in progress.
=> Use task queue for exporter if available

src/components/GrampsjsConnectedComponent.js, src/components/GrampsjsFaces.js
These changes avoid a TypeError when face_detection fails and allow any classes extending GrampsjsConnectedComponent to render even if it's in a failed state.
=> Render GrampsjsFaces even if face_detection fails (fixes #424)

lang/en.json, package-lock.json, package.json, src/LocateControl.js, src/components/GrampsjsFormEditLatLong.js, src/components/GrampsjsFormEditMapLayer.js, src/components/GrampsjsMap.js, src/components/GrampsjsMapTimeSlider.js, src/components/GrampsjsObject.js, src/components/GrampsjsPersonTimeline.js, src/util.js, src/views/GrampsjsViewMap.js
I’ve added a rudimentary [OpenHistoricalMap](https://wiki.openstreetmap.org/wiki/OpenHistoricalMap) layer to all the maps in Gramps Web. The maps still default to the OpenStreetMap layer, but the layer selection control is now available just about anywhere there’s a map.
For now, the OpenHistoricalMap layer just shows everything that’s in OHM, regardless of the date. This would obviously confuse the user. It would be straightforward to filter the map by date, either by installing the interactive [Leaflet time slider](https://github.com/OpenHistoricalMap/leaflet-ohm-timeslider-v2/) plugin or by passing in a date from the surrounding context. I’m unsure of where to get a relevant date, but it seems like it’s within reach.
Here’s my hometown, Loveland, Ohio, and [the late …
=> Add OpenHistoricalMap layer to maps

src/components/GrampsjsAttributes.js, src/components/GrampsjsFormEditAttribute.js, src/components/GrampsjsObject.js, src/components/GrampsjsObjectForm.js
I noticed adding and editing attributes on sources was broken because we didn't handle the distinction between AttributeType and SrcAttributeType.
=> Fix editing source attributes

index.html
This is needed to properly fetch the manifest.json file when Gramps runs behind an authenticating proxy like Pomerium or Cloudflare Zero Trust, as documented here: https://web.dev/articles/add-manifest#link-manifest
Without that the request for the manifest.json file is done without the cookies set by the proxy (CF_AppSession and CF_Authorization in the case of Cloudflare) and the request gets redirected to the proxy login page.
As you can guess, I'm running Gramps behind Cloudflare Zero Trust (and Pomerium before that). I'm running into some issues that I am still investigating, but this one seemed simple enough to solve.
=> Use credentials to request manifest.json file

rollup.config.js
Fixes #517
By default, index.html is cached by the service worker. This breaks the application if it's hosted behind an authentifying proxy which requires periodic revalidation of an auth token. Specifically, once the auth token expires:
1. The index.html is still served from the service worker cache.
2. Subsequent requests (e.g for JS resources) are redirected to the login page of the proxy.
3. That login page is never displayed to the user as index.html has been successfully loaded.
4. All requests but index.html fail, and the app displays a blank page.
This change fixes this behavior by preventing index.html from being cached by the service worker. With that change, once the auth token from the proxy expires:
1. The request for index.html is not served from the service worker cache.
2. …
=> Ignore index.html in service worker cache

src/components/GrampsjsRelationshipChart.js, src/views/GrampsjsViewRelationshipChart.js, src/views/GrampsjsViewTreeChartBase.js
make maximum number  of images displayed in relationship graph UI-configurable. solves #521
=> RelationshipChart: make maxImages configurable

src/components/GrampsjsSysinfo.js, src/views/GrampsjsViewSettings.js
=> Add user information to settings pages

CODE_OF_CONDUCT.md, CONTRIBUTING.md
This adds a standard COC based on [contributor covenant](https://www.contributor-covenant.org/) as well as a CONTRIBUTING.md.
Comments welcome!
Mirrors https://github.com/gramps-project/gramps-web-api/pull/580.
=> Add code of conduct & contributing guidelines

src/components/GrampsjsCitation.js, src/components/GrampsjsEvent.js, src/components/GrampsjsFormNewMedia.js, src/components/GrampsjsFormSelectDate.js, src/components/GrampsjsMediaObject.js, src/components/GrampsjsObjectForm.js, src/util.js, src/views/GrampsjsViewNewCitation.js, src/views/GrampsjsViewNewEvent.js, src/views/GrampsjsViewNewMedia.js, src/views/GrampsjsViewNewPerson.js
This should fix (most of?) the cases where the date property of Gramps obejcts can end up being `null`; it is now set explicitly to an empty date object as required by Gramps 6.
=> Handle date must not be null in Gramps 6 (#631)

src/views/GrampsjsViewTree.js
When you moved the SELECT Home Person widget (#500), the hyperlink on the Family Tree page was still pointing to the User Settings page.
This pull request points it to the Home Page where the SELECT Home Person widget now resides.
=> Fix hyperlink on Family Tree page when no home person is set

lang/en.json, src/components/GrampsjsRect.js, src/components/GrampsjsTooltip.js, src/strings.js, src/views/GrampsjsViewMediaLightbox.js
I added a toggle button that shows/hides (opacity: 0) the person outline rectangles in the lightbox view. When hidden, the person outline rectangles will only show when you hover over them with your mouse.
I tried a switch (mwc-switch instead of mwc-icon-button) first but it took up too much of the limited real estate in the bottom right corner.
This should fix #605.
Feedback or suggestions welcome - this is my first PR for this project.
=> Toggle person outlines on photos

lang/en.json, src/GrampsJs.js, src/SharedStyles.js, src/appState.js, src/components/GrampsjsNoteContent.js, src/components/GrampsjsObject.js, src/components/GrampsjsObjectToc.js, src/strings.js, src/views/GrampsjsViewObjectNotes.js, src/views/GrampsjsViewObjectsDetail.js
This removes the tabbed structure in all object views. To maintain navigatability, on wide screens a table of contens sidebar is added; on mobile, the TOC is reachable by clicking an icon next to section headers; it opens in a modal.
Fixes #666 :smiling_imp:
=> Get rid of tabs in object view

src/components/GrampsjsObject.js, src/components/GrampsjsPlaceNames.js, src/strings.js
This is my first contribution and an attempt to solve issue: https://github.com/gramps-project/gramps-web/issues/27
I have decided to only tackle displaying alternative place names and not implementing edit functionality. This will be added in a future PR.
Any feedback or suggestions welcome
Place view when alternative name is present
Alternative name Tab when alternative name is present
Alternative name Tab when alternative name is present and in edit mode
Place view when alternative name is not present
Place view when alternative name is not present and in edit mode
=> Display alternative place names

src/components/GrampsjsObject.js, src/components/GrampsjsPlaceNames.js
@cajturner I noticed two issues with #566: frontend strings were not passed to the component and the new `alternate_place_names` profile value from the backend wasn't used, so the date display was still wrong. Both is fixed in this PR; you should be able to rebase #713 onto this once merged.
=> Place names: add translation strings and fix date display

src/components/GrampsjsConnectedComponent.js, src/mixins/GrampsjsStaleDataMixin.js, src/views/GrampsjsViewBlog.js, src/views/GrampsjsViewDashboard.js, src/views/GrampsjsViewDnaMatches.js, src/views/GrampsjsViewMap.js, src/views/GrampsjsViewObjectsBase.js, src/views/GrampsjsViewRevisions.js, src/views/GrampsjsViewTasks.js
This changes the behaviour of views when the database is updated. Rather than reloading data eagerly, it loads them lazily when the view becomes visible. This reduces the number of API requests on every change, which should also make changes feel much faster (and reduce problems such as the one mentioned in #718).
Also fixes #565.
=> Lazy loading of updated data in views

src/components/GrampsjsFormEditLatLong.js, src/components/GrampsjsFormEditMapLayer.js, src/components/GrampsjsMap.js, src/components/GrampsjsObject.js
- Removed layer switcher form `GrampsjsEditLatLong` and GrampsjsFormEditMapLayer`
- Add back `layerSwitcher` property on `GrampsjsMap` (this was accidentally removed in the last refactoring)
- Compute year of latest event for each place and use that for the OHM layer
=> Use latest event year for OHM layer in place view map (fixes #467)
