gramps-project/gramps-web

src/GrampsJs.js, src/components/GrampsjsLogin.js, src/lang/de.json, src/lang/en.json, src/util.js
This is a work in progress continuing #88.
=> Localize login page and account for changes in string handling.

src/components/GrampsjsButtonToggle.js, src/lang/de.json, src/lang/en.json, src/views/GrampsjsViewSearch.js
This implements #62 by adding buttons to the search view that allow filtering the results by object type. Screenshot:
=> Filter search results by object type (fixes #62)

src/components/GrampsjsAttributes.js, src/components/GrampsjsCitations.js, src/components/GrampsjsEditableList.js, src/components/GrampsjsFormSelectType.js, src/components/GrampsjsObject.js, src/components/GrampsjsSearchResultList.js, src/components/GrampsjsSourceCitations.js, src/lang/en.json, src/util.js, src/views/GrampsjsViewObject.js, src/views/GrampsjsViewSourceCitations.js
After discussing this implementation with @DavidMStraub in this issue: https://github.com/gramps-project/Gramps.js/issues/118 . I am submitting this pull request to add a custom event type feature.
=> Added custom event type to form select with form validation

src/components/GrampsJsImage.js, src/components/GrampsjsFormUpload.js, src/components/GrampsjsMediaObject.js, src/lang/en.json, src/lang/en_GB.json, src/views/GrampsjsViewMedia.js
This adds a button "Replace file" and allows to replace any media file with a new one.
=> Implement media file replacement (fixes #120)

dev/nginx.conf
Otherwise, server doesn't respond at all
=> Move client_max_body_size to http namespace

src/charts/TreeChart.js
Previously, the dimensions of the Ancestor Tree d3 SVG were estimated as
```
const width = depth * boxWidth + (depth - 1) * gapX + 2 * padding
const height = boxHeight * 2 ** (depth - 1) + (2 ** (depth - 1) - 1) * gapY
```
Which is to say, effectively (depth + gapX) * boxWidth by (boxHeight + gapY) * 2^(depth - 1). This is a reasonable estimate if the ancestor tree is fully populated, but is quite innacurate if the data is more sparse.
This new estimate ensures:
a) that the width is no wider than the total available depth of ancestors available 
b) that the height is representative of the actual height of the nodes rendered 
c) that the tree itself is centered in the SVG, instead of the home person
It would be better to actually inspect what d3 is rendering and get the height/width from …
=> Better estimation of ancestor tree sizes

src/lang/en.json, src/views/GrampsjsViewExport.js
Needs https://github.com/gramps-project/gramps-webapi/pull/373.
=> Add media export button

src/components/GrampsjsFormUpload.js, src/components/GrampsjsUsers.js, src/lang/en.json, src/strings.js, src/views/GrampsjsViewSettings.js
=> Add UI for importing user accounts (fixes #214)

src/GrampsJs.js, src/SharedStyles.js, src/components/GrampsjsFirstRun.js, src/components/GrampsjsFormUpload.js, src/components/GrampsjsTaskProgressIndicator.js, src/strings.js, src/views/GrampsjsViewImport.js
=> Add Import view (fixes #116)

src/GrampsJs.js, src/api.js, src/components/GrampsjsFirstRun.js, src/lang/en.json
This allows creating a tree owner in a multi-tree setup where a tree does not have any users yet - similarly to the existing case for the site admin account.
Depends on https://github.com/gramps-project/gramps-webapi/pull/379.
=> Implement first run assistant for tree owner

src/GrampsJs.js, src/components/GrampsjsMediaObject.js, src/components/GrampsjsTextRecognition.js, src/icons.js, src/lang/en.json, src/strings.js, src/views/GrampsjsViewMedia.js
See https://github.com/gramps-project/gramps-webapi/pull/447
=> UI for OCR

src/GrampsJs.js, src/api.js, src/components/GrampsjsBookmarkButton.js, src/components/GrampsjsBreadcrumbs.js, src/components/GrampsjsCitation.js, src/components/GrampsjsEvent.js, src/components/GrampsjsFamily.js, src/components/GrampsjsMediaObject.js, src/components/GrampsjsNote.js, src/components/GrampsjsObject.js, src/components/GrampsjsPerson.js, src/components/GrampsjsPlace.js, src/components/GrampsjsRepository.js, src/components/GrampsjsSearchResultList.js, src/components/GrampsjsShareUrl.js, src/components/GrampsjsSource.js, src/strings.js, src/util.js, src/views/GrampsjsViewBookmarks.js, src/views/GrampsjsViewRecent.js
=> Add bookmark feature

package-lock.json, src/SharedStyles.js, src/charts/FanChart.js, src/charts/util.js, src/components/GrampsjsFanChart.js, src/strings.js, src/views/GrampsjsViewFanChart.js, src/views/GrampsjsViewTree.js, src/views/GrampsjsViewTreeChartBase.js
This implements fan color based on person properties. I'm quite proud of it!
Implemented:
- Number of events
- Number of notes
- Birth year
- Death year
- Age
- Surname
- Religion
Fixes #349.
=> Implement fan color based on person properties

README.md, src/GrampsJs.js, src/components/GrampsjsFormUpload.js, src/components/GrampsjsImport.js, src/components/GrampsjsImportMedia.js, src/components/GrampsjsSysinfo.js, src/components/GrampsjsUsers.js, src/views/GrampsjsViewAdminSettings.js, src/views/GrampsjsViewSettings.js, src/views/GrampsjsViewUserManagement.js
- Move import to admin settings
- Move user management to separate tab
- Make admin settings and user settings separate views
- Make import and import file separate components
=> Move import to admin settings (fixes #361)

src/views/GrampsjsViewCitations.js
As a user I would like to distinguish different citations from the same source in the citations list by the page.
=> Show page in citations list

src/charts/RelationshipChart.js, src/components/GrampsjsRelationshipChart.js
=> add (limited) images to relship chart

src/SharedStyles.js, src/components/GrampsjsAttributes.js, src/components/GrampsjsCitation.js, src/components/GrampsjsNoteContent.js, src/util.js
=> Make links clickable in more places

lang/en.json, package-lock.json, package.json, src/GrampsJs.js, src/SharedStyles.js, src/api.js, src/components/GrampsjsButtonGroup.js, src/components/GrampsjsChat.js, src/components/GrampsjsChatMessage.js, src/components/GrampsjsChatPermissions.js, src/components/GrampsjsChatPrompt.js, src/components/GrampsjsFilters.js, src/components/GrampsjsMainMenu.js, src/components/GrampsjsMediaStatus.js, src/components/GrampsjsPages.js, src/components/GrampsjsTreeQuotas.js, src/util.js, src/views/GrampsjsViewAdminSettings.js, src/views/GrampsjsViewChat.js, src/views/GrampsjsViewMediaLightbox.js, src/views/GrampsjsViewSearch.js, src/views/GrampsjsViewUserManagement.js
This adds the UI for the proposed chat feature in Web API, see https://github.com/gramps-project/gramps-web-api/pull/539.
What's missing?
=> Add UI for AI Chat

README.md
=> Update README.md, URL typo

lang/en.json, src/SharedStyles.js, src/components/GrampsjsUsers.js, src/views/GrampsjsViewUserManagement.js
Hi,
this is my first contribution and also my first steps in JS.
I added the delete user button to solve issue #304 
I have oriented myself to the edit button and the other dialogs in the users view. Happily, the API was already available.
Feedback is always appreciated 😄 
Delete button inside table
Confirmation dialog
- Add Language strings somewhere to translate into other languages
=> Add delete user button

lang/en.json
=> missing translations

src/charts/RelationshipChart.js
Hi @geostag, I finally got around to replacing the Graphviz connectors in the relationship chart with smooth d3 ones, what do you think?
I grew so fond of the relationship chart that I started thinking we should use the same function also for ancestor/descendant/hourglass - they could just correspond to different data filters rather than chart types. But having something that is left-to-right rather than top-to-bottom would still be nice.
=> Use d3 links for connectors in relationship chart

lang/en.json, src/charts/FanChart.js, src/charts/RelationshipChart.js, src/charts/TreeChart.js, src/components/GrampsjsConnectionChart.js, src/components/GrampsjsFanChart.js, src/components/GrampsjsRelationshipChart.js, src/components/GrampsjsTreeChart.js, src/util.js, src/views/GrampsjsViewDescendantChart.js, src/views/GrampsjsViewFanChart.js, src/views/GrampsjsViewHourglassChart.js, src/views/GrampsjsViewRelationshipChart.js, src/views/GrampsjsViewTreeChart.js, src/views/GrampsjsViewTreeChartBase.js
Fixes #411 
This PR does not attempt to implement a comprehensive, system wide name rending system as proposed by #444. This is only intended to address Charts.
=> Add option to change name display format in charts

src/SharedStyles.js, src/components/GrampsjsAttributes.js, src/components/GrampsjsFilterType.js, src/components/GrampsjsFormChildRef.js, src/components/GrampsjsFormEditAttribute.js, src/components/GrampsjsFormEditFamily.js, src/components/GrampsjsFormEditName.js, src/components/GrampsjsFormEditType.js, src/components/GrampsjsFormEditUrl.js, src/components/GrampsjsFormEventRef.js, src/components/GrampsjsFormNewEvent.js, src/components/GrampsjsFormRepoRef.js, src/components/GrampsjsFormSelectType.js, src/components/GrampsjsFormSurname.js, src/components/GrampsjsObject.js, src/components/GrampsjsObjectForm.js, src/mixins/GrampsjsNewNoteMixin.js, src/views/GrampsjsViewNewFamily.js, src/views/GrampsjsViewNewSource.js
Addressing #470.
Please check my comments.
=> Replace some MWC with MD components

src/components/GrampsjsNames.js
=> Make names list sortable (#562)

src/components/GrampsjsFormEditPlaceName.js, src/components/GrampsjsObject.js, src/components/GrampsjsPlaceNames.js, src/views/GrampsjsViewObject.js
https://github.com/gramps-project/gramps-web/issues/27
Allow place alt names to be added, edited and removed.
=> Allow alternative place name to be edited, added and removed

src/mixins/GrampsjsNewPersonMixin.js, src/views/GrampsjsViewNewPerson.js
https://github.com/gramps-project/gramps-web/issues/227
We want to create a person mixin so we can add the person form to dialogs. This is the first of several changes to allow us to support person creation in multiple places
Tested manually to ensure the new person page still works
=> Create person Mixin
